use truxxit;

DROP TRIGGER IF EXISTS trig_create_customer; 

delimiter //
CREATE TRIGGER trig_create_customer AFTER INSERT ON TEMP_TABLE
       FOR EACH ROW
BEGIN
	   
		INSERT INTO CUSTOMER (CUST_ID, MEMBERSHIP_TYPE) VALUES (NEW.SYS_ID, NEW.MEMBERSHIP);
		INSERT INTO CARD_DETAILS (CUST_ID, CARD_NO, CARD_CVV, CARD_EXPIRY) VALUES (NEW.SYS_ID, NEW.CARDNO, NEW.CARDCVV, NEW.CARDEXP); 
	
END;//
delimiter ;
