use truxxit;

DROP VIEW IF EXISTS RESERVATION_DETAILS;

CREATE VIEW RESERVATION_DETAILS AS
SELECT 	A.LOGIN_ID,
        C.RESERVATION_ID,  
        CONCAT(A.FIRST_NAME,' ',A.LAST_NAME) AS 'CUSTOMER_NAME', 
        C.SOURCE,
        C.DESTINATION,
         CONCAT(F.FIRST_NAME,' ',F.LAST_NAME) AS 'DRIVER_NAME', 
        D.TRUCK_TYPE,
        E.PLAN_NAME
FROM USER A, CUSTOMER B, RESERVATION C, TRUCK D, PLAN_DETAILS E, USER F
WHERE A.SYS_ID = B.CUST_ID
AND B.CUST_ID = C.CUST_ID
AND C.TRUCK_ID = D.TRUCK_ID
AND C.PLAN_ID = E.PLAN_ID
AND C.DRIVER_ID = F.SYS_ID;

-- select * from reservation_details where login_id = 'a';   -- 'C1I2S6';
